# Generated by Django 5.1.4 on 2024-12-20 17:05

import django.db.models.deletion
import wagtail.fields

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("text", 0), ("integer", 1), ("date", 2)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.TextBlock", (), {}),
                            1: ("wagtail.blocks.IntegerBlock", (), {}),
                            2: ("wagtail.blocks.DateBlock", (), {}),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="TestSnippet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("text", 0), ("integer", 1), ("date", 2)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.TextBlock", (), {}),
                            1: ("wagtail.blocks.IntegerBlock", (), {}),
                            2: ("wagtail.blocks.DateBlock", (), {}),
                        },
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
