name: Format

on:
  push:
    branches:
      - main
      - "stable/**"
  pull_request:
    branches: [main]

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: python -Im pip install --user ruff==0.8.4

      - name: Run ruff
        working-directory: ./mlstreamfield
        run: ruff check . --output-format=github
